
Vagrant.configure(2) do |config|
  config.vm.box = "modernIE/w7-ie11"
  config.vm.guest = :windows
  config.vm.hostname = "ICSE-2011-FireDetective"
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |vb|
	 vb.name = "ICSE-2011-FireDetective"
     vb.gui = true
     vb.memory = "1024"
  end

  config.vm.provision :shell, path: "scripts/chocolatey.bat"
  config.vm.provision :shell, path: "scripts/firefox.bat"
  
end
